### ISSUE TITLE
About candidates pool

### ISSUE THREAD

**Issue by reflectionie** [thunlp/Ouroboros#4]
Thank you for your work. I have a few questions regarding the experimental section that I would like to inquire about:

1. In Figure 5, you mentioned that the candidate pool size is 20. In the results shown in Figure 4, is the candidate pool size also 20? If so, will the hit rate be too low because the candidate pool is too sparse? (A pool with a size of 20 is an extremely small number compared to the vocabulary size. Even taking into account locality, this candidate pool size seems to be too small?)
![image](https://github.com/thunlp/Ouroboros/assets/80825638/7482c278-d0e6-4f44-9012-42e957f2048b)
![image](https://github.com/thunlp/Ouroboros/assets/80825638/388ced47-d834-485a-9318-17c0d3a1c857)

2. Could I ask if the **candidates** in your candidate pool can also be regarded as a kind of n-gram, just like lookahead?

**Comment by reflectionie** [comment]
Sorry, I may have some misunderstandings about question 1. I just read the code. The candidate pool size seems to mean that one key corresponds to a maximum of 20 values. Is this understanding correct? If it is correct, what is the approximate size of the key (i.e., the number of entries in the token map)?

**Comment by huangyuxiang03** [comment]
Thanks for asking. 
1. No. The candidate pool size is as same as the window size $W$ recorded in Table 7. Thanks for pointing out the vagueness of our explanations. For each key in the vocalulary, we maintain a siding window whose size is $W$, as well as lookahead decoding. Thus the total capacity of the candidate pool is the size of vocabulary * $W$. The approximate size of key is hard to measure, since they may vary among different models or different tasks. For example, if the model has a relatively large vocabulary and it is evaluated on code generation tasks, only the sliding window of symbol tokens (i.e., `def`, `class`) will be fullfilled. However, when we evaluate the model on natural language tasks (i.e. summarization), nearly all sliding windows are fullfilled. This is exactly what we have observed, which is one of the implicit reason why the experiment of Figure 6 and Table 4 works (since the "activated" parts of candidate pool might be different in each task).
2. Yes. They can be regarded as N-grams of lookahead decoding. They are referenced by a key token with several trailing tokens representing language pieces during generation.

**Comment by reflectionie** [comment]
I think I totally understand, thank you for your detailed explanation!
